services:

  server:
    container_name: server
    restart: always
    build:
      context: server
      args:
        NODE_PORT: 3000
    ports:
      - 3000:3000

    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
